baseURL = "https://pst.org"
theme   = "sk1"
title   = "Paul's Route Notes"
author = "Paul Traina"
copyright = "Copyright © 2023, Paul Traina; all rights reserved."
# paginate = 3
languageCode = "en-us"
DefaultContentLanguage = "en"
cleanDestinationDir = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[permalinks]
  posts = "/posts/:year-:month-:slug/"
  events = "/events/:year-:month-:day-:slug/"

[sitemap]
  changefreq = "hourly"

[Params]
mainSections = ["posts", "events"]
subtitle = "GPS Route Library"

#[markup.tableOfContents]
#endLevel   = 6
#ordered    = false
#startLevel = 1
